### PR TITLE
Http input support

### PR DESCRIPTION
**Pull request by mzahor**
Enables support HTTP links as input source.

### CODE REVIEW

**Comment by AydinAdn** [comment]
Thank you for the support :+1:

**Comment by mzahor** [comment]
Thanks for merging in. I would appreciate if you update the nuget package as well. We use it in our project need these changes.

**Comment by AydinAdn** [comment]
I've released the update on NuGet... enjoy :)

**Comment by mzahor** [comment]
Thank you very much. ;)

**Pull request merged**
